ALTER TABLE boards ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE lists ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;
